[package]
name = "rustty"
version = "0.1.0"
authors = ["Ola <skalle.karlsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2.0"
crossterm = "0.18"
nix = "0.18"